services:
  postgres:
    image: postgres:17.3
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: medit
      POSTGRES_PASSWORD: 7Q0rBpE7PFkr9s
      POSTGRES_DB: medit_db
        #ports:
        #- "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      medit:
        ipv4_address: 172.28.0.7
  medit-backend:
    build:
      context: ../medit-backend
      dockerfile: Dockerfile  
    container_name: medit-backend
      #ports:
      #- "8080:8080"
    depends_on:
      - postgres
    networks:
      medit:
        ipv4_address: 172.28.0.6
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - medit-backend
    networks:
      medit:
        ipv4_address: 172.28.0.5
    restart: unless-stopped

  medit-frontend:
    build:
      context: ../medit-frontend  
    container_name: medit-frontend
      #ports:
      #- "3000:3000"
    depends_on:
      - postgres
    networks:
      medit:
        ipv4_address: 172.28.0.4 

volumes:
  postgres_data:
    driver: local

networks:
  medit:
    name: medit
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16" 
